version: 1
disable_existing_loggers: True

formatters:
  simple:
    format: "%(asctime)s %(levelname)s %(message)s"
    datefmt: '%H:%M:%S'
  standard:
    format: "%(asctime)s %(levelname)s %(name)s %(message)s"
    datefmt: '%Y-%m-%d %H:%M:%S'
  verbose:
    format: '%(asctime)s %(levelname)s %(module)s %(process)d %(thread)d %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  info_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: ./log/info/info.log
    maxBytes: 10485760 # 10MB
    backupCount: 10
    encoding: utf-8
  debug_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: verbose
    filename: ./log/debug/debug.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8
  warning_handler:
    class: logging.handlers.RotatingFileHandler
    level: WARN
    formatter: standard
    filename: ./log/warn/warn.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf-8
  error_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: verbose
    filename: ./log/error/error.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf-8
  critical_handler:
    class: logging.handlers.RotatingFileHandler
    level: CRITICAL
    formatter: verbose
    filename: ./log/crit/crit.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf-8
root:
  level: NOTSET
  handlers: [console, error_handler, critical_handler]
  propagate: yes
loggers:
  __main__:
    level: INFO
    handlers: [console, debug_handler, info_handler, warning_handler, error_handler, critical_handler]
    propagate: no
  src.manager.LogManager:
    level: DEBUG
    handlers: [console, debug_handler, info_handler, warning_handler, error_handler, critical_handler]
    propagate: no
